ALTER TABLE companies          ENABLE ROW LEVEL SECURITY;
ALTER TABLE users              ENABLE ROW LEVEL SECURITY;
ALTER TABLE google_users       ENABLE ROW LEVEL SECURITY;
ALTER TABLE ad_accounts        ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_reports         ENABLE ROW LEVEL SECURITY;
